#!/usr/bin/env sh

# Pre-push hook to run the test suite
# To use this hook, run: make githooks

set -eu

# Flutter uses Git to determine its SDK version; don't let the hook's GIT_DIR
# make it inspect this repository instead of the Flutter SDK repository.
unset GIT_DIR

make test
