include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'

linter:
  rules:
    # Style and Consistency
    prefer_single_quotes: true
    sort_child_properties_last: true
    unnecessary_this: true

    # Safety and Best Practices
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_empty_else: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_super_parameters: true
    prefer_final_locals: true
    avoid_returning_null: true
    avoid_field_initializers_in_const_classes: true

    # Readability
    omit_local_variable_types: false
    require_trailing_commas: true

    # Null safety and defensive coding
    no_leading_underscores_for_local_identifiers: true
    always_specify_types: false # (optional — depends if you want verbose code)

    # Async
    avoid_void_async: true