name: _
publish_to: none
environment:
  sdk: ^3.11.3
workspace:
  - packages/totem_core
  - packages/totem_app
  - packages/totem_web
  - packages/totem_benchmark
dev_dependencies:
  meta: any
  flutter_test:
    sdk: flutter
