name: _
publish_to: none
environment:
  sdk: ^3.11.3
workspace:
  - packages/totem_core
  - packages/totem_app
  - packages/totem_web

dependency_overrides:
  # flutter_webrtc: 1.4.1
  flutter_webrtc:
    git:
      url: https://github.com/flutter-webrtc/flutter-webrtc
      ref: 3931f2f351079cdc2053e3b128a62438455cfc42
