// Mocks generated by Mockito 5.4.6 from annotations
// in totem_app/test/features/sessions/controllers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;
import 'dart:collection' as _i4;
import 'dart:ui' as _i16;

import 'package:livekit_client/src/core/room.dart' as _i2;
import 'package:livekit_client/src/e2ee/options.dart' as _i12;
import 'package:livekit_client/src/events.dart' as _i13;
import 'package:livekit_client/src/managers/event.dart' as _i5;
import 'package:livekit_client/src/participant/participant.dart' as _i8;
import 'package:livekit_client/src/proto/livekit_models.pb.dart' as _i15;
import 'package:livekit_client/src/publication/track_publication.dart' as _i6;
import 'package:livekit_client/src/support/disposable.dart' as _i17;
import 'package:livekit_client/src/track/track.dart' as _i7;
import 'package:livekit_client/src/types/other.dart' as _i10;
import 'package:livekit_client/src/types/participant_permissions.dart' as _i3;
import 'package:livekit_client/src/types/participant_state.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRoom_0 extends _i1.SmartFake implements _i2.Room {
  _FakeRoom_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeParticipantPermissions_1 extends _i1.SmartFake
    implements _i3.ParticipantPermissions {
  _FakeParticipantPermissions_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUnmodifiableMapView_2<K, V> extends _i1.SmartFake
    implements _i4.UnmodifiableMapView<K, V> {
  _FakeUnmodifiableMapView_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_3 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEventsEmitter_4<T1> extends _i1.SmartFake
    implements _i5.EventsEmitter<T1> {
  _FakeEventsEmitter_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEventsListener_5<T1> extends _i1.SmartFake
    implements _i5.EventsListener<T1> {
  _FakeEventsListener_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Participant].
///
/// See the documentation for Mockito's code generation for more information.
class MockParticipant<T extends _i6.TrackPublication<_i7.Track>>
    extends _i1.Mock
    implements _i8.Participant<T> {
  @override
  _i2.Room get room =>
      (super.noSuchMethod(
            Invocation.getter(#room),
            returnValue: _FakeRoom_0(this, Invocation.getter(#room)),
            returnValueForMissingStub: _FakeRoom_0(
              this,
              Invocation.getter(#room),
            ),
          )
          as _i2.Room);

  @override
  Map<String, T> get trackPublications =>
      (super.noSuchMethod(
            Invocation.getter(#trackPublications),
            returnValue: <String, T>{},
            returnValueForMissingStub: <String, T>{},
          )
          as Map<String, T>);

  @override
  double get audioLevel =>
      (super.noSuchMethod(
            Invocation.getter(#audioLevel),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  String get sid =>
      (super.noSuchMethod(
            Invocation.getter(#sid),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#sid)),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#sid),
            ),
          )
          as String);

  @override
  String get identity =>
      (super.noSuchMethod(
            Invocation.getter(#identity),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#identity),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#identity),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#name)),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  _i10.ParticipantKind get kind =>
      (super.noSuchMethod(
            Invocation.getter(#kind),
            returnValue: _i10.ParticipantKind.STANDARD,
            returnValueForMissingStub: _i10.ParticipantKind.STANDARD,
          )
          as _i10.ParticipantKind);

  @override
  _i3.ParticipantPermissions get permissions =>
      (super.noSuchMethod(
            Invocation.getter(#permissions),
            returnValue: _FakeParticipantPermissions_1(
              this,
              Invocation.getter(#permissions),
            ),
            returnValueForMissingStub: _FakeParticipantPermissions_1(
              this,
              Invocation.getter(#permissions),
            ),
          )
          as _i3.ParticipantPermissions);

  @override
  _i4.UnmodifiableMapView<String, String> get attributes =>
      (super.noSuchMethod(
            Invocation.getter(#attributes),
            returnValue: _FakeUnmodifiableMapView_2<String, String>(
              this,
              Invocation.getter(#attributes),
            ),
            returnValueForMissingStub:
                _FakeUnmodifiableMapView_2<String, String>(
                  this,
                  Invocation.getter(#attributes),
                ),
          )
          as _i4.UnmodifiableMapView<String, String>);

  @override
  _i11.ParticipantState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i11.ParticipantState.joining,
            returnValueForMissingStub: _i11.ParticipantState.joining,
          )
          as _i11.ParticipantState);

  @override
  DateTime get joinedAt =>
      (super.noSuchMethod(
            Invocation.getter(#joinedAt),
            returnValue: _FakeDateTime_3(this, Invocation.getter(#joinedAt)),
            returnValueForMissingStub: _FakeDateTime_3(
              this,
              Invocation.getter(#joinedAt),
            ),
          )
          as DateTime);

  @override
  bool get isSpeaking =>
      (super.noSuchMethod(
            Invocation.getter(#isSpeaking),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isMuted =>
      (super.noSuchMethod(
            Invocation.getter(#isMuted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasAudio =>
      (super.noSuchMethod(
            Invocation.getter(#hasAudio),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasVideo =>
      (super.noSuchMethod(
            Invocation.getter(#hasVideo),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.ConnectionQuality get connectionQuality =>
      (super.noSuchMethod(
            Invocation.getter(#connectionQuality),
            returnValue: _i10.ConnectionQuality.unknown,
            returnValueForMissingStub: _i10.ConnectionQuality.unknown,
          )
          as _i10.ConnectionQuality);

  @override
  List<T> get videoTrackPublications =>
      (super.noSuchMethod(
            Invocation.getter(#videoTrackPublications),
            returnValue: <T>[],
            returnValueForMissingStub: <T>[],
          )
          as List<T>);

  @override
  List<T> get audioTrackPublications =>
      (super.noSuchMethod(
            Invocation.getter(#audioTrackPublications),
            returnValue: <T>[],
            returnValueForMissingStub: <T>[],
          )
          as List<T>);

  @override
  _i12.EncryptionType get firstTrackEncryptionType =>
      (super.noSuchMethod(
            Invocation.getter(#firstTrackEncryptionType),
            returnValue: _i12.EncryptionType.kNone,
            returnValueForMissingStub: _i12.EncryptionType.kNone,
          )
          as _i12.EncryptionType);

  @override
  bool get isEncrypted =>
      (super.noSuchMethod(
            Invocation.getter(#isEncrypted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasInfo =>
      (super.noSuchMethod(
            Invocation.getter(#hasInfo),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set audioLevel(double? value) => super.noSuchMethod(
    Invocation.setter(#audioLevel, value),
    returnValueForMissingStub: null,
  );

  @override
  set sid(String? value) => super.noSuchMethod(
    Invocation.setter(#sid, value),
    returnValueForMissingStub: null,
  );

  @override
  set identity(String? value) => super.noSuchMethod(
    Invocation.setter(#identity, value),
    returnValueForMissingStub: null,
  );

  @override
  set metadata(String? value) => super.noSuchMethod(
    Invocation.setter(#metadata, value),
    returnValueForMissingStub: null,
  );

  @override
  set lastSpokeAt(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#lastSpokeAt, value),
    returnValueForMissingStub: null,
  );

  @override
  set isSpeaking(bool? speaking) => super.noSuchMethod(
    Invocation.setter(#isSpeaking, speaking),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(
            Invocation.getter(#isDisposed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get disposeFuncCount =>
      (super.noSuchMethod(
            Invocation.getter(#disposeFuncCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i5.EventsEmitter<_i13.ParticipantEvent> get events =>
      (super.noSuchMethod(
            Invocation.getter(#events),
            returnValue: _FakeEventsEmitter_4<_i13.ParticipantEvent>(
              this,
              Invocation.getter(#events),
            ),
            returnValueForMissingStub:
                _FakeEventsEmitter_4<_i13.ParticipantEvent>(
                  this,
                  Invocation.getter(#events),
                ),
          )
          as _i5.EventsEmitter<_i13.ParticipantEvent>);

  @override
  void updateConnectionQuality(_i10.ConnectionQuality? quality) =>
      super.noSuchMethod(
        Invocation.method(#updateConnectionQuality, [quality]),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<bool> updateFromInfo(_i15.ParticipantInfo? info) =>
      (super.noSuchMethod(
            Invocation.method(#updateFromInfo, [info]),
            returnValue: _i14.Future<bool>.value(false),
            returnValueForMissingStub: _i14.Future<bool>.value(false),
          )
          as _i14.Future<bool>);

  @override
  _i3.ParticipantPermissions? setPermissions(
    _i3.ParticipantPermissions? newValue,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setPermissions, [newValue]),
            returnValueForMissingStub: null,
          )
          as _i3.ParticipantPermissions?);

  @override
  void updateName(String? name) => super.noSuchMethod(
    Invocation.method(#updateName, [name]),
    returnValueForMissingStub: null,
  );

  @override
  void addTrackPublication(T? pub) => super.noSuchMethod(
    Invocation.method(#addTrackPublication, [pub]),
    returnValueForMissingStub: null,
  );

  @override
  T? getTrackPublicationBySid(String? sid) =>
      (super.noSuchMethod(
            Invocation.method(#getTrackPublicationBySid, [sid]),
            returnValueForMissingStub: null,
          )
          as T?);

  @override
  T? getTrackPublicationByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getTrackPublicationByName, [name]),
            returnValueForMissingStub: null,
          )
          as T?);

  @override
  List<T> getTrackPublications() =>
      (super.noSuchMethod(
            Invocation.method(#getTrackPublications, []),
            returnValue: <T>[],
            returnValueForMissingStub: <T>[],
          )
          as List<T>);

  @override
  T? getTrackPublicationBySource(_i10.TrackSource? source) =>
      (super.noSuchMethod(
            Invocation.method(#getTrackPublicationBySource, [source]),
            returnValueForMissingStub: null,
          )
          as T?);

  @override
  bool isCameraEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isCameraEnabled, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isMicrophoneEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isMicrophoneEnabled, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isScreenShareEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isScreenShareEnabled, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isScreenShareAudioEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isScreenShareAudioEnabled, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i14.Future<bool> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i14.Future<bool>.value(false),
            returnValueForMissingStub: _i14.Future<bool>.value(false),
          )
          as _i14.Future<bool>);

  @override
  void addListener(_i16.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i16.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void onDispose(_i17.OnDisposeFunc? func) => super.noSuchMethod(
    Invocation.method(#onDispose, [func]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.EventsListener<_i13.ParticipantEvent> createListener({
    bool? synchronized = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createListener, [], {
              #synchronized: synchronized,
            }),
            returnValue: _FakeEventsListener_5<_i13.ParticipantEvent>(
              this,
              Invocation.method(#createListener, [], {
                #synchronized: synchronized,
              }),
            ),
            returnValueForMissingStub:
                _FakeEventsListener_5<_i13.ParticipantEvent>(
                  this,
                  Invocation.method(#createListener, [], {
                    #synchronized: synchronized,
                  }),
                ),
          )
          as _i5.EventsListener<_i13.ParticipantEvent>);
}
