//  dart format off
//  GENERATED CODE - DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stdin
//  OpenAPI spec version: 3.1.0

import 'dart:async';
import 'dart:convert';
import 'package:degenerate_runtime/degenerate_runtime.dart';
import '../models/mobile_space_detail_schema.dart';
import '../models/paged_mobile_space_detail_schema.dart';
import '../models/session_detail_schema.dart';
import '../models/session_feedback_schema.dart';
import '../models/space_schema.dart';
import '../models/summary_spaces_schema.dart';

/// SpacesApi operations.
///
/// All operations return [ApiResult] - use pattern matching to handle
/// success, error, and exception cases.
final class SpacesApi with ApiExecutor {
  const SpacesApi(this.apiConfig);

  @override
  final ApiConfig apiConfig;

  /// Subscribe To Space
  ///
  /// `POST /api/mobile/protected/spaces/subscribe/{space_slug}`
  Future<ApiResult<bool, Never>> totemSpacesMobileApiSubscribeToSpace({
    required String spaceSlug,
    RequestOptions? options,
  }) async {
    final headers = <String, String>{...apiConfig.defaultHeaders};

    final request = ApiRequest(
      method: 'POST',
      path:
          '/api/mobile/protected/spaces/subscribe/${Uri.encodeComponent(spaceSlug)}',
      headers: headers,
      options: options,
    );

    return execute(
      request,
      onSuccess: (response) {
        return jsonDecode(response.body) as bool;
      },
    );
  }

  /// Unsubscribe To Space
  ///
  /// `DELETE /api/mobile/protected/spaces/subscribe/{space_slug}`
  Future<ApiResult<bool, Never>> totemSpacesMobileApiUnsubscribeToSpace({
    required String spaceSlug,
    RequestOptions? options,
  }) async {
    final headers = <String, String>{...apiConfig.defaultHeaders};

    final request = ApiRequest(
      method: 'DELETE',
      path:
          '/api/mobile/protected/spaces/subscribe/${Uri.encodeComponent(spaceSlug)}',
      headers: headers,
      options: options,
    );

    return execute(
      request,
      onSuccess: (response) {
        return jsonDecode(response.body) as bool;
      },
    );
  }

  /// List Subscriptions
  ///
  /// `GET /api/mobile/protected/spaces/subscribe`
  Future<ApiResult<List<SpaceSchema>, Never>>
  totemSpacesMobileApiListSubscriptions({RequestOptions? options}) async {
    final headers = <String, String>{...apiConfig.defaultHeaders};

    final request = ApiRequest(
      method: 'GET',
      path: '/api/mobile/protected/spaces/subscribe',
      headers: headers,
      options: options,
    );

    return execute(
      request,
      onSuccess: (response) {
        final json = jsonDecode(response.body) as List<dynamic>;
        return json
            .map((e) => SpaceSchema.fromJson(e as Map<String, dynamic>))
            .toList();
      },
    );
  }

  /// List Spaces
  ///
  /// `GET /api/mobile/protected/spaces/`
  Future<ApiResult<PagedMobileSpaceDetailSchema, Never>>
  totemSpacesMobileApiListSpaces({
    int? limit,
    int? offset,
    RequestOptions? options,
  }) async {
    final queryParameters = <String, String>{
      ...apiConfig.defaultQueryParameters,
    };
    final queryParametersList = <ApiQueryParameter>[];
    if (limit != null) queryParameters['limit'] = limit.toString();
    if (offset != null) queryParameters['offset'] = offset.toString();

    final headers = <String, String>{...apiConfig.defaultHeaders};

    final request = ApiRequest(
      method: 'GET',
      path: '/api/mobile/protected/spaces/',
      headers: headers,
      queryParameters: queryParameters,
      queryParametersList: queryParametersList,
      options: options,
    );

    return execute(
      request,
      onSuccess: (response) {
        return PagedMobileSpaceDetailSchema.fromJson(
          jsonDecode(response.body) as Map<String, dynamic>,
        );
      },
    );
  }

  /// Get Space Detail
  ///
  /// `GET /api/mobile/protected/spaces/space/{space_slug}`
  Future<ApiResult<MobileSpaceDetailSchema, Never>>
  totemSpacesMobileApiGetSpaceDetail({
    required String spaceSlug,
    RequestOptions? options,
  }) async {
    final headers = <String, String>{...apiConfig.defaultHeaders};

    final request = ApiRequest(
      method: 'GET',
      path:
          '/api/mobile/protected/spaces/space/${Uri.encodeComponent(spaceSlug)}',
      headers: headers,
      options: options,
    );

    return execute(
      request,
      onSuccess: (response) {
        return MobileSpaceDetailSchema.fromJson(
          jsonDecode(response.body) as Map<String, dynamic>,
        );
      },
    );
  }

  /// Get Keeper Spaces
  ///
  /// `GET /api/mobile/protected/spaces/keeper/{slug}/`
  Future<ApiResult<List<MobileSpaceDetailSchema>, Never>>
  totemSpacesMobileApiGetKeeperSpaces({
    required String slug,
    RequestOptions? options,
  }) async {
    final headers = <String, String>{...apiConfig.defaultHeaders};

    final request = ApiRequest(
      method: 'GET',
      path: '/api/mobile/protected/spaces/keeper/${Uri.encodeComponent(slug)}/',
      headers: headers,
      options: options,
    );

    return execute(
      request,
      onSuccess: (response) {
        final json = jsonDecode(response.body) as List<dynamic>;
        return json
            .map(
              (e) =>
                  MobileSpaceDetailSchema.fromJson(e as Map<String, dynamic>),
            )
            .toList();
      },
    );
  }

  /// Get Session Detail
  ///
  /// `GET /api/mobile/protected/spaces/session/{event_slug}`
  Future<ApiResult<SessionDetailSchema, Never>>
  totemSpacesMobileApiGetSessionDetail({
    required String eventSlug,
    RequestOptions? options,
  }) async {
    final headers = <String, String>{...apiConfig.defaultHeaders};

    final request = ApiRequest(
      method: 'GET',
      path:
          '/api/mobile/protected/spaces/session/${Uri.encodeComponent(eventSlug)}',
      headers: headers,
      options: options,
    );

    return execute(
      request,
      onSuccess: (response) {
        return SessionDetailSchema.fromJson(
          jsonDecode(response.body) as Map<String, dynamic>,
        );
      },
    );
  }

  /// Post Session Feedback
  ///
  /// `POST /api/mobile/protected/spaces/session/{event_slug}/feedback`
  Future<ApiResult<void, Never>> totemSpacesMobileApiPostSessionFeedback({
    required String eventSlug,
    required SessionFeedbackSchema body,
    RequestOptions? options,
  }) async {
    final headers = <String, String>{...apiConfig.defaultHeaders};
    headers['Content-Type'] = 'application/json';

    final request = ApiRequest(
      method: 'POST',
      path:
          '/api/mobile/protected/spaces/session/${Uri.encodeComponent(eventSlug)}/feedback',
      headers: headers,
      body: jsonEncode(body.toJson()),
      options: options,
    );

    return execute(request, onSuccess: (_) {});
  }

  /// Get Sessions History
  ///
  /// `GET /api/mobile/protected/spaces/sessions/history`
  Future<ApiResult<List<SessionDetailSchema>, Never>>
  totemSpacesMobileApiGetSessionsHistory({RequestOptions? options}) async {
    final headers = <String, String>{...apiConfig.defaultHeaders};

    final request = ApiRequest(
      method: 'GET',
      path: '/api/mobile/protected/spaces/sessions/history',
      headers: headers,
      options: options,
    );

    return execute(
      request,
      onSuccess: (response) {
        final json = jsonDecode(response.body) as List<dynamic>;
        return json
            .map((e) => SessionDetailSchema.fromJson(e as Map<String, dynamic>))
            .toList();
      },
    );
  }

  /// Get Recommended Spaces
  ///
  /// `GET /api/mobile/protected/spaces/sessions/recommended`
  Future<ApiResult<List<SessionDetailSchema>, Never>>
  totemSpacesMobileApiGetRecommendedSpaces({
    int? limit,
    List<String>? body,
    RequestOptions? options,
  }) async {
    final queryParameters = <String, String>{
      ...apiConfig.defaultQueryParameters,
    };
    final queryParametersList = <ApiQueryParameter>[];
    if (limit != null) queryParameters['limit'] = limit.toString();

    final headers = <String, String>{...apiConfig.defaultHeaders};
    headers['Content-Type'] = 'application/json';

    final request = ApiRequest(
      method: 'GET',
      path: '/api/mobile/protected/spaces/sessions/recommended',
      headers: headers,
      queryParameters: queryParameters,
      queryParametersList: queryParametersList,
      body: jsonEncode(body),
      options: options,
    );

    return execute(
      request,
      onSuccess: (response) {
        final json = jsonDecode(response.body) as List<dynamic>;
        return json
            .map((e) => SessionDetailSchema.fromJson(e as Map<String, dynamic>))
            .toList();
      },
    );
  }

  /// Get Spaces Summary
  ///
  /// `GET /api/mobile/protected/spaces/summary`
  Future<ApiResult<SummarySpacesSchema, Never>>
  totemSpacesMobileApiGetSpacesSummary({RequestOptions? options}) async {
    final headers = <String, String>{...apiConfig.defaultHeaders};

    final request = ApiRequest(
      method: 'GET',
      path: '/api/mobile/protected/spaces/summary',
      headers: headers,
      options: options,
    );

    return execute(
      request,
      onSuccess: (response) {
        return SummarySpacesSchema.fromJson(
          jsonDecode(response.body) as Map<String, dynamic>,
        );
      },
    );
  }

  /// Rsvp Confirm
  ///
  /// `POST /api/mobile/protected/spaces/rsvp/{event_slug}`
  Future<ApiResult<SessionDetailSchema, Never>>
  totemSpacesMobileApiRsvpConfirm({
    required String eventSlug,
    RequestOptions? options,
  }) async {
    final headers = <String, String>{...apiConfig.defaultHeaders};

    final request = ApiRequest(
      method: 'POST',
      path:
          '/api/mobile/protected/spaces/rsvp/${Uri.encodeComponent(eventSlug)}',
      headers: headers,
      options: options,
    );

    return execute(
      request,
      onSuccess: (response) {
        return SessionDetailSchema.fromJson(
          jsonDecode(response.body) as Map<String, dynamic>,
        );
      },
    );
  }

  /// Rsvp Cancel
  ///
  /// `DELETE /api/mobile/protected/spaces/rsvp/{event_slug}`
  Future<ApiResult<SessionDetailSchema, Never>> totemSpacesMobileApiRsvpCancel({
    required String eventSlug,
    RequestOptions? options,
  }) async {
    final headers = <String, String>{...apiConfig.defaultHeaders};

    final request = ApiRequest(
      method: 'DELETE',
      path:
          '/api/mobile/protected/spaces/rsvp/${Uri.encodeComponent(eventSlug)}',
      headers: headers,
      options: options,
    );

    return execute(
      request,
      onSuccess: (response) {
        return SessionDetailSchema.fromJson(
          jsonDecode(response.body) as Map<String, dynamic>,
        );
      },
    );
  }
}
