//  dart format off
//  GENERATED CODE - DO NOT MODIFY BY HAND
//
//  Generated by degenerate from openapi.json
//  OpenAPI spec version: 3.1.0

final class EndReason {
  const EndReason._(this.value);

  factory EndReason.fromJson(String json) {
    return switch (json) {
      'keeper_ended' => keeperEnded,
      'keeper_absent' => keeperAbsent,
      'room_empty' => roomEmpty,
      _ => EndReason._(json),
    };
  }

  static const EndReason keeperEnded = EndReason._('keeper_ended');

  static const EndReason keeperAbsent = EndReason._('keeper_absent');

  static const EndReason roomEmpty = EndReason._('room_empty');

  static const List<EndReason> values = [keeperEnded, keeperAbsent, roomEmpty];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) || other is EndReason && other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'EndReason($value)';
  }
}
