//  dart format off
//  GENERATED CODE - DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stdin
//  OpenAPI spec version: 3.1.0

import 'package:collection/collection.dart';

final class LivekitOrderSchema {
  const LivekitOrderSchema({required this.order});

  factory LivekitOrderSchema.fromJson(Map<String, dynamic> json) {
    return LivekitOrderSchema(
      order: (json['order'] as List<dynamic>).map((e) => e as String).toList(),
    );
  }

  final List<String> order;

  Map<String, dynamic> toJson() {
    return {'order': order};
  }

  static bool canParse(Map<String, dynamic> json) {
    return json.containsKey('order');
  }

  LivekitOrderSchema copyWith({List<String>? order}) {
    return LivekitOrderSchema(order: order ?? this.order);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is LivekitOrderSchema &&
            const ListEquality<dynamic>().equals(order, other.order);
  }

  @override
  int get hashCode {
    return Object.hashAll(order).hashCode;
  }

  @override
  String toString() {
    return 'LivekitOrderSchema(order: $order)';
  }
}
