//  dart format off
//  GENERATED CODE - DO NOT MODIFY BY HAND
//
//  Generated by degenerate from openapi.json
//  OpenAPI spec version: 3.1.0

import 'package:collection/collection.dart';
import 'next_session_schema.dart';
import 'public_user_schema.dart';

final class MobileSpaceDetailSchema {
  const MobileSpaceDetailSchema({
    required this.slug,
    required this.title,
    required this.imageLink,
    required this.shortDescription,
    required this.content,
    required this.author,
    required this.category,
    required this.subscribers,
    required this.recurring,
    required this.price,
    required this.nextEvents,
  });

  factory MobileSpaceDetailSchema.fromJson(Map<String, dynamic> json) {
    return MobileSpaceDetailSchema(
      slug: json['slug'] as String,
      title: json['title'] as String,
      imageLink: json['image_link'] as String,
      shortDescription: json['short_description'] as String,
      content: json['content'] as String,
      author: PublicUserSchema.fromJson(json['author'] as Map<String, dynamic>),
      category: json['category'] as String,
      subscribers: (json['subscribers'] as num).toInt(),
      recurring: json['recurring'] as String,
      price: (json['price'] as num).toInt(),
      nextEvents: (json['next_events'] as List<dynamic>)
          .map((e) => NextSessionSchema.fromJson(e as Map<String, dynamic>))
          .toList(),
    );
  }

  final String slug;

  final String title;

  final String? imageLink;

  final String shortDescription;

  final String content;

  final PublicUserSchema author;

  final String? category;

  final int subscribers;

  final String? recurring;

  final int price;

  final List<NextSessionSchema> nextEvents;

  Map<String, dynamic> toJson() {
    return {
      'slug': slug,
      'title': title,
      'image_link': ?imageLink,
      'short_description': shortDescription,
      'content': content,
      'author': author.toJson(),
      'category': ?category,
      'subscribers': subscribers,
      'recurring': ?recurring,
      'price': price,
      'next_events': nextEvents.map((e) => e.toJson()).toList(),
    };
  }

  static bool canParse(Map<String, dynamic> json) {
    return json.containsKey('slug') &&
        json['slug'] is String &&
        json.containsKey('title') &&
        json['title'] is String &&
        json.containsKey('image_link') &&
        json['image_link'] is String &&
        json.containsKey('short_description') &&
        json['short_description'] is String &&
        json.containsKey('content') &&
        json['content'] is String &&
        json.containsKey('author') &&
        json.containsKey('category') &&
        json['category'] is String &&
        json.containsKey('subscribers') &&
        json['subscribers'] is num &&
        json.containsKey('recurring') &&
        json['recurring'] is String &&
        json.containsKey('price') &&
        json['price'] is num &&
        json.containsKey('next_events');
  }

  MobileSpaceDetailSchema copyWith({
    String? slug,
    String? title,
    String? Function()? imageLink,
    String? shortDescription,
    String? content,
    PublicUserSchema? author,
    String? Function()? category,
    int? subscribers,
    String? Function()? recurring,
    int? price,
    List<NextSessionSchema>? nextEvents,
  }) {
    return MobileSpaceDetailSchema(
      slug: slug ?? this.slug,
      title: title ?? this.title,
      imageLink: imageLink != null ? imageLink() : this.imageLink,
      shortDescription: shortDescription ?? this.shortDescription,
      content: content ?? this.content,
      author: author ?? this.author,
      category: category != null ? category() : this.category,
      subscribers: subscribers ?? this.subscribers,
      recurring: recurring != null ? recurring() : this.recurring,
      price: price ?? this.price,
      nextEvents: nextEvents ?? this.nextEvents,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is MobileSpaceDetailSchema &&
            slug == other.slug &&
            title == other.title &&
            imageLink == other.imageLink &&
            shortDescription == other.shortDescription &&
            content == other.content &&
            author == other.author &&
            category == other.category &&
            subscribers == other.subscribers &&
            recurring == other.recurring &&
            price == other.price &&
            const ListEquality<dynamic>().equals(nextEvents, other.nextEvents);
  }

  @override
  int get hashCode {
    return Object.hash(
      slug,
      title,
      imageLink,
      shortDescription,
      content,
      author,
      category,
      subscribers,
      recurring,
      price,
      Object.hashAll(nextEvents),
    );
  }

  @override
  String toString() {
    return 'MobileSpaceDetailSchema(slug: $slug, title: $title, imageLink: $imageLink, shortDescription: $shortDescription, content: $content, author: $author, category: $category, subscribers: $subscribers, recurring: $recurring, price: $price, nextEvents: $nextEvents)';
  }
}
