//  dart format off
//  GENERATED CODE - DO NOT MODIFY BY HAND
//
//  Generated by degenerate from openapi.json
//  OpenAPI spec version: 3.1.0

import 'meeting_provider_enum.dart';

final class NextSessionSchema {
  const NextSessionSchema({
    required this.slug,
    required this.start,
    required this.link,
    required this.title,
    required this.seatsLeft,
    required this.duration,
    required this.meetingProvider,
    required this.calLink,
    required this.attending,
    required this.cancelled,
    required this.open,
    required this.joinable,
  });

  factory NextSessionSchema.fromJson(Map<String, dynamic> json) {
    return NextSessionSchema(
      slug: json['slug'] as String,
      start: DateTime.parse(json['start'] as String),
      link: json['link'] as String,
      title: json['title'] as String,
      seatsLeft: (json['seats_left'] as num).toInt(),
      duration: (json['duration'] as num).toInt(),
      meetingProvider: MeetingProviderEnum.fromJson(
        json['meeting_provider'] as String,
      ),
      calLink: json['cal_link'] as String,
      attending: json['attending'] as bool,
      cancelled: json['cancelled'] as bool,
      open: json['open'] as bool,
      joinable: json['joinable'] as bool,
    );
  }

  final String slug;

  final DateTime start;

  final String link;

  final String? title;

  final int seatsLeft;

  final int duration;

  final MeetingProviderEnum meetingProvider;

  final String calLink;

  final bool attending;

  final bool cancelled;

  final bool open;

  final bool joinable;

  Map<String, dynamic> toJson() {
    return {
      'slug': slug,
      'start': start.toIso8601String(),
      'link': link,
      'title': ?title,
      'seats_left': seatsLeft,
      'duration': duration,
      'meeting_provider': meetingProvider.toJson(),
      'cal_link': calLink,
      'attending': attending,
      'cancelled': cancelled,
      'open': open,
      'joinable': joinable,
    };
  }

  static bool canParse(Map<String, dynamic> json) {
    return json.containsKey('slug') &&
        json['slug'] is String &&
        json.containsKey('start') &&
        json['start'] is String &&
        json.containsKey('link') &&
        json['link'] is String &&
        json.containsKey('title') &&
        json['title'] is String &&
        json.containsKey('seats_left') &&
        json['seats_left'] is num &&
        json.containsKey('duration') &&
        json['duration'] is num &&
        json.containsKey('meeting_provider') &&
        json.containsKey('cal_link') &&
        json['cal_link'] is String &&
        json.containsKey('attending') &&
        json['attending'] is bool &&
        json.containsKey('cancelled') &&
        json['cancelled'] is bool &&
        json.containsKey('open') &&
        json['open'] is bool &&
        json.containsKey('joinable') &&
        json['joinable'] is bool;
  }

  NextSessionSchema copyWith({
    String? slug,
    DateTime? start,
    String? link,
    String? Function()? title,
    int? seatsLeft,
    int? duration,
    MeetingProviderEnum? meetingProvider,
    String? calLink,
    bool? attending,
    bool? cancelled,
    bool? open,
    bool? joinable,
  }) {
    return NextSessionSchema(
      slug: slug ?? this.slug,
      start: start ?? this.start,
      link: link ?? this.link,
      title: title != null ? title() : this.title,
      seatsLeft: seatsLeft ?? this.seatsLeft,
      duration: duration ?? this.duration,
      meetingProvider: meetingProvider ?? this.meetingProvider,
      calLink: calLink ?? this.calLink,
      attending: attending ?? this.attending,
      cancelled: cancelled ?? this.cancelled,
      open: open ?? this.open,
      joinable: joinable ?? this.joinable,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is NextSessionSchema &&
            slug == other.slug &&
            start == other.start &&
            link == other.link &&
            title == other.title &&
            seatsLeft == other.seatsLeft &&
            duration == other.duration &&
            meetingProvider == other.meetingProvider &&
            calLink == other.calLink &&
            attending == other.attending &&
            cancelled == other.cancelled &&
            open == other.open &&
            joinable == other.joinable;
  }

  @override
  int get hashCode {
    return Object.hash(
      slug,
      start,
      link,
      title,
      seatsLeft,
      duration,
      meetingProvider,
      calLink,
      attending,
      cancelled,
      open,
      joinable,
    );
  }

  @override
  String toString() {
    return 'NextSessionSchema(slug: $slug, start: $start, link: $link, title: $title, seatsLeft: $seatsLeft, duration: $duration, meetingProvider: $meetingProvider, calLink: $calLink, attending: $attending, cancelled: $cancelled, open: $open, joinable: $joinable)';
  }
}
