//  dart format off
//  GENERATED CODE - DO NOT MODIFY BY HAND
//
//  Generated by degenerate from openapi.json
//  OpenAPI spec version: 3.1.0

import 'package:collection/collection.dart';
import 'mobile_space_detail_schema.dart';

final class PagedMobileSpaceDetailSchema {
  const PagedMobileSpaceDetailSchema({
    required this.items,
    required this.count,
  });

  factory PagedMobileSpaceDetailSchema.fromJson(Map<String, dynamic> json) {
    return PagedMobileSpaceDetailSchema(
      items: (json['items'] as List<dynamic>)
          .map(
            (e) => MobileSpaceDetailSchema.fromJson(e as Map<String, dynamic>),
          )
          .toList(),
      count: (json['count'] as num).toInt(),
    );
  }

  final List<MobileSpaceDetailSchema> items;

  final int count;

  Map<String, dynamic> toJson() {
    return {'items': items.map((e) => e.toJson()).toList(), 'count': count};
  }

  static bool canParse(Map<String, dynamic> json) {
    return json.containsKey('items') &&
        json.containsKey('count') &&
        json['count'] is num;
  }

  PagedMobileSpaceDetailSchema copyWith({
    List<MobileSpaceDetailSchema>? items,
    int? count,
  }) {
    return PagedMobileSpaceDetailSchema(
      items: items ?? this.items,
      count: count ?? this.count,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is PagedMobileSpaceDetailSchema &&
            const ListEquality<dynamic>().equals(items, other.items) &&
            count == other.count;
  }

  @override
  int get hashCode {
    return Object.hash(Object.hashAll(items), count);
  }

  @override
  String toString() {
    return 'PagedMobileSpaceDetailSchema(items: $items, count: $count)';
  }
}
