//  dart format off
//  GENERATED CODE - DO NOT MODIFY BY HAND
//
//  Generated by degenerate from openapi.json
//  OpenAPI spec version: 3.1.0

/// Machine-readable error codes. Clients switch on these, not on messages.
/// Add new codes here as needed — the OpenAPI spec will update automatically.
final class ErrorCode {
  const ErrorCode._(this.value);

  factory ErrorCode.fromJson(String json) {
    return switch (json) {
      'not_in_room' => notInRoom,
      'not_keeper' => notKeeper,
      'not_current_speaker' => notCurrentSpeaker,
      'not_next_speaker' => notNextSpeaker,
      'banned' => banned,
      'invalid_transition' => invalidTransition,
      'room_not_active' => roomNotActive,
      'room_not_waiting' => roomNotWaiting,
      'room_already_ended' => roomAlreadyEnded,
      'invalid_participant_order' => invalidParticipantOrder,
      'keeper_not_in_room' => keeperNotInRoom,
      'stale_version' => staleVersion,
      'not_joinable' => notJoinable,
      'livekit_error' => livekitError,
      'not_found' => notFound,
      _ => ErrorCode._(json),
    };
  }

  static const ErrorCode notInRoom = ErrorCode._('not_in_room');

  static const ErrorCode notKeeper = ErrorCode._('not_keeper');

  static const ErrorCode notCurrentSpeaker = ErrorCode._('not_current_speaker');

  static const ErrorCode notNextSpeaker = ErrorCode._('not_next_speaker');

  static const ErrorCode banned = ErrorCode._('banned');

  static const ErrorCode invalidTransition = ErrorCode._('invalid_transition');

  static const ErrorCode roomNotActive = ErrorCode._('room_not_active');

  static const ErrorCode roomNotWaiting = ErrorCode._('room_not_waiting');

  static const ErrorCode roomAlreadyEnded = ErrorCode._('room_already_ended');

  static const ErrorCode invalidParticipantOrder = ErrorCode._(
    'invalid_participant_order',
  );

  static const ErrorCode keeperNotInRoom = ErrorCode._('keeper_not_in_room');

  static const ErrorCode staleVersion = ErrorCode._('stale_version');

  static const ErrorCode notJoinable = ErrorCode._('not_joinable');

  static const ErrorCode livekitError = ErrorCode._('livekit_error');

  static const ErrorCode notFound = ErrorCode._('not_found');

  static const List<ErrorCode> values = [
    notInRoom,
    notKeeper,
    notCurrentSpeaker,
    notNextSpeaker,
    banned,
    invalidTransition,
    roomNotActive,
    roomNotWaiting,
    roomAlreadyEnded,
    invalidParticipantOrder,
    keeperNotInRoom,
    staleVersion,
    notJoinable,
    livekitError,
    notFound,
  ];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) || other is ErrorCode && other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'ErrorCode($value)';
  }
}

/// Structured error. Clients switch on `code`, display `message`.
/// `detail` is optional extra context for debugging.
final class RoomErrorResponse {
  const RoomErrorResponse({
    required this.code,
    required this.message,
    this.detail,
  });

  factory RoomErrorResponse.fromJson(Map<String, dynamic> json) {
    return RoomErrorResponse(
      code: ErrorCode.fromJson(json['code'] as String),
      message: json['message'] as String,
      detail: json['detail'] as String?,
    );
  }

  /// Machine-readable error codes. Clients switch on these, not on messages.
  /// Add new codes here as needed — the OpenAPI spec will update automatically.
  final ErrorCode code;

  final String message;

  final String? detail;

  Map<String, dynamic> toJson() {
    return {'code': code.toJson(), 'message': message, 'detail': ?detail};
  }

  static bool canParse(Map<String, dynamic> json) {
    return json.containsKey('code') &&
        json.containsKey('message') &&
        json['message'] is String;
  }

  RoomErrorResponse copyWith({
    ErrorCode? code,
    String? message,
    String? Function()? detail,
  }) {
    return RoomErrorResponse(
      code: code ?? this.code,
      message: message ?? this.message,
      detail: detail != null ? detail() : this.detail,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is RoomErrorResponse &&
            code == other.code &&
            message == other.message &&
            detail == other.detail;
  }

  @override
  int get hashCode {
    return Object.hash(code, message, detail);
  }

  @override
  String toString() {
    return 'RoomErrorResponse(code: $code, message: $message, detail: $detail)';
  }
}
