//  dart format off
//  GENERATED CODE - DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stdin
//  OpenAPI spec version: 3.1.0

final class ValidatePinSchema {
  const ValidatePinSchema({required this.email, required this.pin});

  factory ValidatePinSchema.fromJson(Map<String, dynamic> json) {
    return ValidatePinSchema(
      email: json['email'] as String,
      pin: json['pin'] as String,
    );
  }

  final String email;

  final String pin;

  Map<String, dynamic> toJson() {
    return {'email': email, 'pin': pin};
  }

  static bool canParse(Map<String, dynamic> json) {
    return json.containsKey('email') &&
        json['email'] is String &&
        json.containsKey('pin') &&
        json['pin'] is String;
  }

  ValidatePinSchema copyWith({String? email, String? pin}) {
    return ValidatePinSchema(email: email ?? this.email, pin: pin ?? this.pin);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is ValidatePinSchema && email == other.email && pin == other.pin;
  }

  @override
  int get hashCode {
    return Object.hash(email, pin);
  }

  @override
  String toString() {
    return 'ValidatePinSchema(email: $email, pin: $pin)';
  }
}
