//  dart format off
//  GENERATED CODE - DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stdin
//  OpenAPI spec version: 3.1.0

final class WaitingRoomDetail {
  const WaitingRoomDetail({this.type = 'waiting_room'});

  factory WaitingRoomDetail.fromJson(Map<String, dynamic> json) {
    return WaitingRoomDetail(
      type: json.containsKey('type') ? json['type'] as String : 'waiting_room',
    );
  }

  final String type;

  Map<String, dynamic> toJson() {
    return {'type': type};
  }

  static bool canParse(Map<String, dynamic> json) {
    return true;
  }

  WaitingRoomDetail copyWith({String Function()? type}) {
    return WaitingRoomDetail(type: type != null ? type() : this.type);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is WaitingRoomDetail && type == other.type;
  }

  @override
  int get hashCode {
    return type.hashCode;
  }

  @override
  String toString() {
    return 'WaitingRoomDetail(type: $type)';
  }
}
