// Compose the per-flavor .env for each package from the layered sources in
// config/. This is the single source of truth for runtime config: .env is a
// Flutter asset, read once at startup by AppConfig (totem_core). Local builds
// (the Makefile env-* targets) and CI (the setup-environment / build-web
// actions) all call this, so they can't drift.
//
// Layering (last value of each key wins) for a given (flavor, platform):
//   config/common.env
//     -> config/<flavor>.env
//       -> config/<platform>/common.env
//         -> config/<platform>/<flavor>.env
//           -> config/<flavor>.local.env              (development only)
//             -> config/<platform>/<flavor>.local.env (development only)
// Missing layers are skipped. .local layers apply only to development, so
// staging/production stay deterministic from committed files. See config/README.md.
//
// Usage: dart scripts/setup_env.dart <development|staging|production>

// OK to use print
// ignore_for_file: avoid_print

import 'dart:io';

const _flavors = {'development', 'staging', 'production'};

// platform -> the package whose .env it generates.
const _packages = {'app': 'totem_app', 'web': 'totem_web'};

void main(List<String> args) {
  final flavor = args.isEmpty ? '' : args.first;
  if (!_flavors.contains(flavor)) {
    stderr.writeln(
      'usage: dart scripts/setup_env.dart <${_flavors.join('|')}>',
    );
    exit(64);
  }

  // scripts/setup_env.dart -> repo root is two levels up.
  final repoRoot = File(Platform.script.toFilePath()).parent.parent.path;
  final configDir = '$repoRoot/config';

  for (final entry in _packages.entries) {
    final platform = entry.key;
    final env = _compose(configDir, flavor, platform);
    final out = File('$repoRoot/packages/${entry.value}/.env');
    out.writeAsStringSync(_render(env, flavor, platform));
    print('setup_env: wrote ${out.path} ($flavor)');
  }
}

/// Layer file paths in increasing precedence; later files override earlier keys.
List<String> _layers(String configDir, String flavor, String platform) {
  final layers = [
    '$configDir/common.env',
    '$configDir/$flavor.env',
    '$configDir/$platform/common.env',
    '$configDir/$platform/$flavor.env',
  ];
  // .local layers apply to development only, so staging/production stay
  // deterministic from committed files.
  if (flavor == 'development') {
    layers
      ..add('$configDir/$flavor.local.env')
      ..add('$configDir/$platform/$flavor.local.env');
  }
  return layers;
}

/// Merge the existing layers into a key->value map; last assignment wins.
Map<String, String> _compose(String configDir, String flavor, String platform) {
  final env = <String, String>{};
  for (final path in _layers(configDir, flavor, platform)) {
    final file = File(path);
    if (!file.existsSync()) continue;
    for (final line in file.readAsLinesSync()) {
      final trimmed = line.trimLeft();
      if (trimmed.isEmpty || trimmed.startsWith('#')) continue;
      final eq = line.indexOf('=');
      if (eq < 0) continue;
      final key = line
          .substring(0, eq)
          .replaceFirst(RegExp(r'^\s*export\s+'), '')
          .trim();
      env[key] = line.substring(eq + 1); // value kept verbatim (quotes intact)
    }
  }
  return env;
}

String _render(Map<String, String> env, String flavor, String platform) {
  final keys = env.keys.toList()..sort(); // sorted for stable diffs
  final buffer = StringBuffer()
    ..writeln('# Generated by scripts/setup_env.dart ($flavor / $platform).')
    ..writeln('# Do not edit — change the layered sources in config/ instead.');
  for (final key in keys) {
    buffer.writeln('$key=${env[key]}');
  }
  return buffer.toString();
}
