name: flutter-build-android
description: Builds an apk or appbundle
branding:
  icon: box
  color: green
inputs:
  working-directory:
    description: The root directory of the flutter app within this repository
    default: ./packages/totem_app
  build-cmd:
    description: The full build command, can be used to add arguments
    default: flutter build appbundle --release
  keystore-base64:
    description: "keystore with which to sign the app"
    required: true
  keystore-password:
    description: "The password for the playstore key used to sign the app"
    required: true

runs:
  using: "composite"
  steps:
    # Assumes the Flutter/Java toolchain is already set up by the calling
    # workflow (see .github/actions/setup-environment).
    - name: Decode keystore and create jks and properties file for signing the app
      shell: bash
      run: |
        echo "$KEYSTORE" | base64 --decode > app/keystore.jks
        echo "storeFile=keystore.jks" >> key.properties
        echo "keyAlias=release" >> key.properties
        echo "storePassword=$KEYSTORE_PASSWORD" >> key.properties
        echo "keyPassword=$KEYSTORE_PASSWORD" >> key.properties
      env:
        KEYSTORE: ${{ inputs.keystore-base64 }}
        KEYSTORE_PASSWORD: ${{ inputs.keystore-password }}
      working-directory: ${{ inputs.working-directory }}/android

    - name: Build
      run: ${{ inputs.build-cmd }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
