name: totem_web
description: "Guided introspection groups."
publish_to: "none"
version: 0.0.69+69
resolution: workspace

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  totem_core:
    path: ../totem_core
  dio: ^5.9.2
  degenerate_dio: ^0.4.1
  http: ^1.6.0
  web: ^1.1.1

  sentry_flutter: ^9.21.0

  # State Management
  flutter_riverpod: ^3.3.1

  go_router: ^17.2.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
