name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Flutter Analysis"]
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: subosito/flutter-action@v2.23.0
        with:
          channel: stable

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          firebase_options: ${{ secrets.FIREBASE_OPTIONS_B64 }}
          flavor: staging

      - name: Install dependencies for totem_core
        working-directory: packages/totem_core
        run: flutter pub get

      - name: Install dependencies for totem_web
        working-directory: packages/totem_web
        run: flutter pub get

      - name: Build
        working-directory: packages/totem_web
        run: flutter build web --wasm

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/totem_web/build/web
          force_orphan: true
          user_name: "github-ci[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Publish to gh-pages"
