name: Flutter Analysis
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  package-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup build environment
        uses: ./.github/actions/setup-environment
        with:
          firebase_options: ${{ secrets.FIREBASE_OPTIONS_B64 }}
          flavor: staging

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: |
          dart format --set-exit-if-changed .

      - name: Run analysis
        run: flutter analyze

      - name: Run core tests
        working-directory: packages/totem_core
        run: flutter test

      - name: Run app tests
        working-directory: packages/totem_app
        run: flutter test

      - name: Run web tests
        working-directory: packages/totem_web
        run: flutter test --platform chrome
