// dart format off
// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by degenerate from openapi.json
// OpenAPI spec version: 3.1.0

import 'package:degenerate_runtime/degenerate_runtime.dart';
import 'totem_mobile_api_security.dart';
import '../apis/default_api.dart';
import '../apis/users_api.dart';
import '../apis/spaces_api.dart';
import '../apis/blog_api.dart';
import '../apis/meetings_api.dart';
import '../apis/rooms_api.dart';

/// Root SDK client providing access to all API groups.
///
/// ```dart
/// final sdk = TotemMobileApi(ApiConfig(client: myClient));
/// sdk.$default.totemApiMobileApiRegisterFcmToken();
/// ```
final class TotemMobileApi {
  final ApiConfig _config;

  TotemMobileApi(this._config);

  late final DefaultApi $default = DefaultApi(_config);
  late final UsersApi users = UsersApi(_config);
  late final SpacesApi spaces = SpacesApi(_config);
  late final BlogApi blog = BlogApi(_config);
  late final MeetingsApi meetings = MeetingsApi(_config);
  late final RoomsApi rooms = RoomsApi(_config);

  TotemMobileApi withJWTAuth(String token) => TotemMobileApi(TotemMobileSecurity.applyJWTAuth(_config, token));
}
